[workspace]
members = ["."]
resolver = "2"

[dist]
cargo-dist-version = "0.17.0"
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-pc-windows-msvc"
]

installers = ["shell", "powershell", "homebrew"]
ci = ["github"]

release-notes = "CHANGELOG.md"