name: Release Binaries

on:
  workflow_run:
    workflows: ["Release PyPI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release-binaries:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      startsWith(github.event.workflow_run.head_branch, 'v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary_name: ztn
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: ztn
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: ztn.exe

    steps:
      - name: Checkout repository at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename and Pack Binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.binary_name }}-${{ matrix.target }}.zip ${{ matrix.binary_name }}
          else
            tar -czvf ../../../${{ matrix.binary_name }}-${{ matrix.target }}.tar.gz ${{ matrix.binary_name }}
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.binary_name }}-${{ matrix.target }}.*
          tag_name: ${{ github.event.workflow_run.head_branch }}
